name: SHIPcal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - iapws
  - pvlib-python
  - pysolar
  - coverage
  - pytest
  - pytest-cov
  - tox
  - pip:
    - pylama[all]